"""
╔══════════════════════════════════════════════════════════════════════════════════╗
║                                                                                  ║
║  🌊🔱  SIREN — Shannon Intelligence Recon & Exploitation Nexus  🔱🌊           ║
║                                                                                  ║
║  The fusion of the most complete offensive arsenal (SIREN)                ║
║  and the most intelligent autonomous pentester ever created (Shannon AI).        ║
║                                                                                  ║
║  Shannon provides the BRAIN. SIREN provides the BODY.                        ║
║  Together they are SIREN — the perfect predator.                                 ║
║                                                                                  ║
║  Pipeline: RECON → ANALYSIS → EXPLOITATION → POST-EXPLOIT → REPORTING           ║
║  Agents:   13 autonomous agents across 5 OWASP domains                           ║
║  Arsenal:  711+ tools via 50 MCP servers                                         ║
║  Evasion:  640+ semantic rules (KRAKEN ENGINE)                                   ║
║  Brain:    Multi-tier AI (small/medium/large models)                             ║
║  Modules:  Network, Scanner, Recon, Payloads, Exploits, Fuzzer,                  ║
║            Crypto, Auth, Workspace, Orchestrator, Mobile Engine,                 ║
║            APK Analyzer, Dynamic Mobile, Mobile Payloads,                        ║
║            Attack Graph Engine, Threat Intel Correlator — 46,000+ lines         ║
║                                                                                  ║
║  "The abyss now thinks. And it already knows your vulnerabilities."              ║
║                                                                                  ║
╚══════════════════════════════════════════════════════════════════════════════════╝
"""

# ── Core Pipeline & Agents ──────────────────────────────────────
from .agents import (
    AGENT_PHASE_MAP,
    AGENTS,
    ALL_VULN_TYPES,
    AgentDefinition,
    PhaseName,
    VulnType,
)

# ── API Security Engine ────────────────────────────────────────
from .api_security import (
    APIAuditResult,
    APIEndpoint,
    APISecurityFinding,
    APISecurityHTTP,
    APISeverity,
    APIVulnCategory,
    AuthGateBypassScanner,
    BrokenAccessControlScanner,
    ChannelBypassScanner,
    DataExposureFinding,
    DataExposureScanner,
    HeaderPermutationFuzzer,
    JWTSecurityScanner,
    RateLimitScanner,
    ScopeLevel,
    SirenAPISecurityEngine,
    UserEnumerationScanner,
)

# ── APK / IPA Static Analyzer ──────────────────────────────────
from .apk_analyzer import (
    AnalysisDepth,
    BinaryXMLParser,
    CertificateAnalysis,
    CertificateAnalyzer,
    ComponentType,
    DexAnalysis,
    DexDeepAnalyzer,
    DexStringExtractor,
    ELFAnalyzer,
    FullAnalysisResult,
    IPAPlistAnalyzer,
    ManifestAnalysis,
    ManifestAnalyzer,
    NativeLibAnalysis,
    NetworkSecurityAnalysis,
    NetworkSecurityConfigAnalyzer,
    PlayStorePolicyChecker,
    SirenAPKAnalyzer,
    StorageAnalysis,
    StoragePatternAnalyzer,
)

# ── ARSENAL: Extended Weapons Systems (TIER 1 — UNIQUE) ──────
from .arsenal import (
    # AD Attack
    ADFinding,
    ADReport,
    # IoT Engine
    AMQPAnalyzer,
    # DAST Engine
    AuthenticatedScanner,
    # Cloud Attack
    AWSExploiter,
    AzureExploiter,
    BACnetScanner,
    # Firmware Analyzer
    BinaryDelta,
    # Protocol Dissector
    BinaryFieldExtractor,
    BloodHoundAnalyzer,
    CloudAsset,
    CloudCredential,
    CloudCredentialHarvester,
    CloudFinding,
    CloudPrivEscChain,
    CloudPrivEscPath,
    CoAPExploiter,
    # Container Security
    ContainerAuditReport,
    ContainerFinding,
    CrawlerEngine,
    # Network Exploiter
    CredentialHarvester,
    DASTFinding,
    DASTReport,
    # LLM Attack
    DataExfiltrator,
    DefaultCredDB,
    # Supply Chain
    DependencyGraphBuilder,
    DockerfileAnalyzer,
    DomainInfo,
    EntropyAnalyzer,
    FirmwareFinding,
    FirmwareMetadata,
    FirmwareReport,
    FuzzingSeedGenerator,
    GCPExploiter,
    # GraphQL Engine
    GraphQLField,
    GraphQLSchema,
    IAMAnalyzer,
    IntrospectionQueryBuilder,
    IoTDevice,
    IoTFinding,
    IoTFingerprinter,
    IoTReport,
    JailbreakEngine,
    KubernetesAnalyzer,
    LDAPEnumerator,
    LicenseAuditor,
    LLMFinding,
    LLMSecurityReport,
    ManifestParser,
    MetadataExploiter,
    ModbusExploiter,
    MQTTExploiter,
    NetworkFinding,
    NetworkMapper,
    NetworkReport,
    ParameterFuzzer,
    PromptInjector,
    ProtocolAttacker,
    ProtocolField,
    ProtocolSignature,
    QueryGenerator,
    S3BucketScanner,
    # SAST Engine
    SASTFinding,
    SASTReport,
    SASTScanConfig,
    ServiceExploiter,
    SirenADAttacker,
    SirenCloudAttacker,
    SirenContainerSecurity,
    SirenDASTEngine,
    SirenFirmwareAnalyzer,
    SirenGraphQLEngine,
    SirenIoTEngine,
    SirenLLMAttacker,
    SirenNetworkExploiter,
    SirenProtocolDissector,
    SirenSASTEngine,
    SirenSupplyChain,
    # WebSocket Engine
    SirenWebSocketEngine,
    SourceDetector,
    SupplyChainFinding,
    SupplyChainReport,
    SystemPromptExtractor,
    TaintFlow,
    TunnelManager,
    UPnPScanner,
    WSFrame,
    WSFuzzGenerator,
    WSMessage,
    WSReport,
)

# ── Attack Graph Engine (UNIQUE) ───────────────────────────────
from .attack_graph import (
    AttackChain,
    AttackEdge,
    AttackGraph,
    AttackGraphBuilder,
    AttackNode,
    AttackSurfaceSnapshot,
    BlastRadiusResult,
    EdgeType,
    GraphAnalysisResult,
    LynchpinResult,
    NodeType,
    RiskTier,
    SirenAttackGraphAnalyzer,
)

# ── Authentication Attack Engine ───────────────────────────────
from .auth_engine import (
    AccountEnumerator,
    AuthFingerprinter,
    BruteForceEngine,
    CookieForger,
    DefaultCredentialScanner,
    MFABypassEngine,
    OAuthExploitEngine,
    PasswordResetPoison,
    PasswordSprayer,
    RegistrationAbuseEngine,
    SessionAnalyzer,
    SessionFixationEngine,
    SessionPredictionEngine,
    SirenAuthEngine,
    TokenReplayEngine,
)

# ── AUTOMATION: Campaign & Continuous Ops (TIER 3) ───────────
from .automation import (
    # Continuous Monitor
    Alert,
    AlertSeverity,
    # Campaign Manager
    Campaign,
    CampaignPersistence,
    CampaignPhase,
    CampaignTask,
    CampaignTemplates,
    ContentDiffer,
    # Result Correlator
    CorrelatedFinding,
    CorrelationRule,
    CrossScanPattern,
    DeduplicationEngine,
    MonitorTarget,
    SirenCampaignManager,
    SirenContinuousMonitor,
    SirenResultCorrelator,
)

# ── Cloud & JWT Advanced Scanner ───────────────────────────────
from .cloud_jwt_scanner import (
    CloudFunctionScanner,
    CORSAdvancedScanner,
    JSONInteropScanner,
    JWTAdvancedScanner,
)

# ── CORTEX: Cognitive Core (TIER 0 — UNIQUE) ─────────────────
from .cortex import (
    # Attack Planner
    ActionLibrary,
    # Attack Persona
    AttackPersona,
    AttackPlan,
    # Bayesian Engine
    BayesianNetwork,
    BayesianNode,
    BehaviorSimulator,
    BeliefState,
    ChainCandidate,
    ChainExecutor,
    ChainOptimizer,
    ChainScorer,
    ChainSynthesizer,
    # Cognitive Reasoner
    DeductiveEngine,
    DNAExtractor,
    # Adversarial ML
    EvasionGenerator,
    EvasionResult,
    Evidence,
    EvidenceCollector,
    # Exploit Synthesis
    ExploitPrimitive,
    FeatureAnalyzer,
    GeneticComparator,
    GraphQueryEngine,
    Hypothesis,
    HypothesisRanker,
    InferenceRule,
    KnowledgeEdge,
    KnowledgeGraph,
    # Knowledge Graph
    KnowledgeNode,
    LineageTracker,
    MLModelProber,
    MutationAnalyzer,
    PersonaLibrary,
    PersonaStrategySelector,
    PerturbationEngine,
    PlanOptimizer,
    PlanSearchEngine,
    PosteriorCalculator,
    PredictiveGenetics,
    PrimitiveMapper,
    ReasoningChain,
    ReasoningReport,
    ReasoningResult,
    SirenAdversarialML,
    SirenAttackPersonaEngine,
    SirenAttackPlanner,
    SirenBayesianEngine,
    SirenCognitiveReasoner,
    SirenExploitSynthesis,
    SirenKnowledgeGraph,
    SirenVulnDNA,
    # Vuln DNA
    VulnGenome,
)

# ── Cryptographic Attack Engine ────────────────────────────────
from .crypto import (
    CBCBitFlipEngine,
    CipherAnalyzer,
    ECBDetector,
    HashEngine,
    JWTAttackEngine,
    KeyStrengthAnalyzer,
    PaddingOracleEngine,
    RandomnessAnalyzer,
    SirenCryptoEngine,
    TimingAttackEngine,
    TLSScanner,
)

# ── Dynamic Mobile Analysis & Runtime Exploitation ─────────────
from .dynamic_mobile import (
    BroadcastExploiter,
    ContentProviderExploiter,
    ContentProviderResult,
    DeepLinkFuzzer,
    DeepLinkResult,
    DynamicTestResult,
    FridaScriptLibrary,
    HookResult,
    HookType,
    IPCExploitEngine,
    MemoryScanner,
    MemoryScanResult,
    ScreenshotEngine,
    SirenDynamicAnalyzer,
)
from .dynamic_mobile import (
    ExploitResult as MobileExploitResult,
)
from .engine import (
    SIREN_TOOLS,
    PRICING,
    PROMPT_TEMPLATES,
    AbyssalEngine,
    AIProvider,
    AIResponse,
    ContextManager,
    DeliverableExtractor,
    EngineConfig,
)

# ── EVASION: WAF Bypass & Payload Transformation ─────────────
from .evasion import (
    # WAF Bypass
    BypassResult,
    BypassTechnique,
    # Payload Obfuscator
    CMDObfuscator,
    EncodingChainer,
    HTMLObfuscator,
    # IDS Evasion
    IDSEvasionReport,
    IDSFinding,
    JSObfuscator,
    ObfuscationReport,
    ObfuscationResult,
    PacketFragmenter,
    PayloadMutator,
    PayloadTransformer,
    PowerShellObfuscator,
    ProtocolAbuser,
    SessionSplitter,
    ShellObfuscator,
    SirenIDSEvasion,
    SirenPayloadObfuscator,
    SirenWAFBypass,
    SQLObfuscator,
    TimingEvader,
    TrafficMixer,
    WAFBypassReport,
    WAFFingerprinter,
    WAFProfile,
)

# ── Exploitation Engine ────────────────────────────────────────
from .exploits import (
    AuthBypassExploiter,
    ExploitCategory,
    ExploitOrchestrator,
    ExploitResult,
    ExploitSeverity,
    ExploitStatus,
    SQLiExploiter,
    SSRFExploiter,
    XSSExploiter,
)

# ── Smart Fuzzer ───────────────────────────────────────────────
from .fuzzer import (
    Corpus,
    CoverageTracker,
    CrashReport,
    CrashTriager,
    DifferentialFuzzer,
    FuzzerConfig,
    FuzzerStats,
    FuzzTarget,
    GrammarFuzzer,
    MutationStrategy,
    Mutator,
    ParameterDiscovery,
    SirenFuzzer,
    WordlistGenerator,
)

# ── INTELLIGENCE: Defensive Mirror & Narrative (TIER 2 — UNIQUE)
from .intelligence import (
    AttackTimeline,
    AudienceAdapter,
    CodePatchGenerator,
    ConfigFixGenerator,
    # CVE Predictor
    CVEDatabase,
    # Social Engineering
    DomainLookalikeGen,
    # OSINT Correlator
    DorkEngine,
    # Deep Fingerprint
    FingerprintResult,
    FirewallRuleGenerator,
    IdentityResolver,
    IDSSignatureGenerator,
    # Threat Hunting
    IOCExtractor,
    # Attack Narrative
    NarrativeChapter,
    NarrativeEngine,
    OSINTGraph,
    PhishingTemplateGen,
    PlaybookLibrary,
    PredictionReport,
    PretextBuilder,
    SIGMARuleGenerator,
    SignatureDB,
    SirenAttackNarrative,
    SirenCVEPredictor,
    SirenDeepFingerprint,
    SirenDefensiveMirror,
    SirenOSINTCorrelator,
    SirenSocialEngineer,
    SirenThreatHunter,
    SMiShingGen,
    SocialEngReport,
    STIXExporter,
    ThreatSIGMARuleGenerator,
    VishingScriptGen,
    # Defensive Mirror
    WAFRuleGenerator,
    YARARuleGenerator,
)

# ── META: Self-Evolution & Learning (TIER 5 — UNIQUE) ────────
from .meta import (
    # Performance Profiler
    BottleneckInfo,
    EvolutionDB,
    FalsePositiveLearner,
    OperationProfile,
    OptimizationSuggestion,
    PatternLearner,
    PayloadEvolver,
    # Strategy DB
    SimilarityEngine,
    SirenPerformanceProfiler,
    SirenSelfEvolution,
    SirenStrategyDB,
    StrategyChain,
    StrategyOptimizer,
    StrategyPersistence,
    StrategyRecommendation,
    StrategyRecord,
    TargetProfiler,
    TechniqueRanker,
    ThroughputTracker,
    Timer,
)

# ── Mobile Engine ───────────────────────────────────────────────
from .mobile_engine import (
    DANGEROUS_PERMISSIONS,
    OWASP_MOBILE_TOP10,
    ADBBridge,
    APKHandler,
    APKInfo,
    AppState,
    DeviceInfo,
    DeviceManager,
    DeviceState,
    EmulatorManager,
    FridaEngine,
    IPAHandler,
    IPAInfo,
    LogcatAnalyzer,
    LogcatEntry,
    MobileFinding,
    MobileTestConfig,
    MobileTestResult,
    Platform,
    RootStatus,
    SecurityLevel,
    SirenMobileController,
    TrafficCapture,
    TrafficInterceptor,
)

# ── Mobile Payloads Arsenal ────────────────────────────────────
from .mobile_payloads import (
    ADBPayloads,
    BroadcastPayloads,
    ContentProviderPayloads,
    DeepLinkPayloads,
    FridaPayloads,
    IntentPayloads,
    MobilePayload,
    NetworkPayloads,
    PayloadSet,
    PayloadSeverity,
    SirenPayloadGenerator,
    WebViewPayloads,
    iOSPayloads,
)
from .mobile_payloads import (
    PayloadCategory as MobilePayloadCategory,
)
from .models import ModelTier, resolve_model

# ── Network & HTTP Engine ───────────────────────────────────────
from .network import (
    AdaptiveRateLimiter,
    CookieJar,
    DNSResolver,
    HARRecorder,
    InterceptorChain,
    ProxyConfig,
    ProxyRotator,
    RequestConfig,
    ResponseCache,
    ResponseData,
    ServerFingerprinter,
    SirenHTTPClient,
    TLSAnalyzer,
)

# ── Orchestrator, Error Classification & Smart Pipeline ───────
from .orchestrator import (
    ActivityStream,
    ClassifiedError,
    ErrorClassifier,
    ErrorCode,
    ErrorSeverity,
    ExploitationGate,
    ExploitDecision,
    ProgressSnapshot,
    ProgressTracker,
    PromptContext,
    PromptManager,
    SirenOrchestrator,
    TOTPGenerator,
)

# ── OUTPUT: Compliance, Risk & Remediation (TIER 4) ──────────
from .output import (
    # Risk Scorer
    BusinessContext,
    # Compliance Mapper
    ComplianceControl,
    ComplianceGap,
    ComplianceReport,
    ComplianceStandard,
    # Remediation Generator
    FixTemplate,
    PriorityQueue,
    RemediationPlan,
    RemediationStep,
    RiskFactor,
    RiskMatrix,
    RiskScore,
    SirenComplianceMapper,
    SirenRemediationGenerator,
    SirenRiskScorer,
)

# ── Payload Generator ──────────────────────────────────────────
from .payloads import (
    AuthBypassPayloads,
    CMDiPayloads,
    DeserializationPayloads,
    EvasionLevel,
    HeaderInjectionPayloads,
    InjectionContext,
    LDAPIPayloads,
    NoSQLiPayloads,
    PathTraversalPayloads,
    Payload,
    PayloadArsenal,
    PayloadCategory,
    PayloadEncoder,
    SQLiPayloads,
    SSRFPayloads,
    SSTIPayloads,
    XSSPayloads,
    XXEPayloads,
)

# ── Pentest ↔ API Security Integration ─────────────────────────
from .pentest_api_integration import (
    AgentResult,
    PentestAPISecurityAgent,
)

# ── Pentest Engine ─────────────────────────────────────────────
from .pentest_engine import (
    AttackVector as PentestAttackVector,
)
from .pentest_engine import (
    BusinessLogicScanner,
    ComplianceChecker,
    MassAssignmentScanner,
    OWASPAPITop10,
    OWASPTop10,
    PentestConfig,
    PentestFinding,
    PentestPhase,
    PentestResult,
    PentestSeverity,
    RaceConditionScanner,
    SirenPentestEngine,
)
from .pipeline import Pipeline, PipelineResult, PipelineState

# ── Reconnaissance Engine ──────────────────────────────────────
from .recon import (
    DirectoryResult,
    PortResult,
    ReconConfig,
    ReconResult,
    SirenRecon,
    SSLInfo,
    SubdomainResult,
    TechFingerprint,
    WAFResult,
)
from .reporter import AbyssalReporter

# ── Vulnerability Scanner ──────────────────────────────────────
from .scanner import (
    Confidence,
    FormParser,
    InjectionPoint,
    ScanConfig,
    ScanResult,
    Severity,
    SirenScanner,
    VulnCategory,
    VulnFinding,
)

# ── Threat Intelligence Correlation Engine (UNIQUE) ───────────
from .threat_intel import (
    ATTACKMapping,
    ComplianceFramework,
    ComplianceViolation,
    ExploitPrediction,
    IndustryVertical,
    KillChainPhase,
    SirenThreatIntel,
    ThreatActorCorrelation,
    ThreatHuntQuery,
    ThreatIntelReport,
    ThreatLevel,
)

# ── Workspace, Checkpoints & Session ──────────────────────────
from .workspace import (
    AuditEvent,
    AuditEventType,
    AuditLogger,
    CheckpointAction,
    CheckpointInfo,
    ConfigFileLoader,
    ConfigSchema,
    DeliverableInfo,
    DeliverableManager,
    DeliverableType,
    DeliverableValidator,
    GitCheckpointManager,
    SessionState,
    SessionStateMachine,
    WorkspaceInfo,
    WorkspaceManager,
    WorkspaceStatus,
)

__all__ = [
    # Core
    "AbyssalEngine",
    "AIProvider",
    "AIResponse",
    "ContextManager",
    "DeliverableExtractor",
    "EngineConfig",
    "SIREN_TOOLS",
    "PRICING",
    "PROMPT_TEMPLATES",
    "AGENTS",
    "AGENT_PHASE_MAP",
    "AgentDefinition",
    "PhaseName",
    "VulnType",
    "ALL_VULN_TYPES",
    "Pipeline",
    "PipelineState",
    "PipelineResult",
    "AbyssalReporter",
    "ModelTier",
    "resolve_model",
    # Network
    "SirenHTTPClient",
    "AdaptiveRateLimiter",
    "ProxyConfig",
    "ProxyRotator",
    "RequestConfig",
    "ResponseData",
    "ResponseCache",
    "ServerFingerprinter",
    "TLSAnalyzer",
    "HARRecorder",
    "InterceptorChain",
    "CookieJar",
    "DNSResolver",
    # Scanner
    "SirenScanner",
    "ScanConfig",
    "ScanResult",
    "VulnFinding",
    "VulnCategory",
    "Severity",
    "Confidence",
    "InjectionPoint",
    "FormParser",
    # Recon
    "SirenRecon",
    "ReconConfig",
    "ReconResult",
    "SubdomainResult",
    "PortResult",
    "TechFingerprint",
    "SSLInfo",
    "WAFResult",
    "DirectoryResult",
    # Payloads
    "PayloadArsenal",
    "PayloadEncoder",
    "Payload",
    "PayloadCategory",
    "InjectionContext",
    "EvasionLevel",
    "SQLiPayloads",
    "XSSPayloads",
    "SSRFPayloads",
    "CMDiPayloads",
    "SSTIPayloads",
    "XXEPayloads",
    "AuthBypassPayloads",
    "DeserializationPayloads",
    "HeaderInjectionPayloads",
    "LDAPIPayloads",
    "NoSQLiPayloads",
    "PathTraversalPayloads",
    # Exploits
    "ExploitOrchestrator",
    "SQLiExploiter",
    "XSSExploiter",
    "SSRFExploiter",
    "AuthBypassExploiter",
    "ExploitResult",
    "ExploitCategory",
    "ExploitSeverity",
    "ExploitStatus",
    # Fuzzer
    "SirenFuzzer",
    "FuzzTarget",
    "FuzzerConfig",
    "FuzzerStats",
    "MutationStrategy",
    "Mutator",
    "CoverageTracker",
    "Corpus",
    "CrashReport",
    "CrashTriager",
    "DifferentialFuzzer",
    "GrammarFuzzer",
    "ParameterDiscovery",
    "WordlistGenerator",
    # Crypto
    "SirenCryptoEngine",
    "JWTAttackEngine",
    "HashEngine",
    "CipherAnalyzer",
    "TLSScanner",
    "PaddingOracleEngine",
    "TimingAttackEngine",
    "RandomnessAnalyzer",
    "KeyStrengthAnalyzer",
    "CBCBitFlipEngine",
    "ECBDetector",
    # Auth
    "SirenAuthEngine",
    "AuthFingerprinter",
    "AccountEnumerator",
    "BruteForceEngine",
    "PasswordSprayer",
    "SessionAnalyzer",
    "CookieForger",
    "SessionFixationEngine",
    "SessionPredictionEngine",
    "OAuthExploitEngine",
    "MFABypassEngine",
    "TokenReplayEngine",
    "PasswordResetPoison",
    "DefaultCredentialScanner",
    "RegistrationAbuseEngine",
    # Workspace / Checkpoints / Session
    "WorkspaceManager",
    "WorkspaceStatus",
    "WorkspaceInfo",
    "GitCheckpointManager",
    "CheckpointAction",
    "CheckpointInfo",
    "SessionStateMachine",
    "SessionState",
    "DeliverableManager",
    "DeliverableValidator",
    "DeliverableType",
    "DeliverableInfo",
    "AuditLogger",
    "AuditEvent",
    "AuditEventType",
    "ConfigFileLoader",
    "ConfigSchema",
    # Orchestrator / Error Classification / Pipeline
    "SirenOrchestrator",
    "ErrorClassifier",
    "ErrorCode",
    "ErrorSeverity",
    "ClassifiedError",
    "ExploitationGate",
    "ExploitDecision",
    "PromptManager",
    "PromptContext",
    "TOTPGenerator",
    "ActivityStream",
    "ProgressTracker",
    "ProgressSnapshot",
    # Mobile Engine
    "Platform",
    "DeviceState",
    "AppState",
    "SecurityLevel",
    "RootStatus",
    "DeviceInfo",
    "APKInfo",
    "IPAInfo",
    "LogcatEntry",
    "MobileFinding",
    "TrafficCapture",
    "ADBBridge",
    "APKHandler",
    "IPAHandler",
    "FridaEngine",
    "LogcatAnalyzer",
    "DeviceManager",
    "TrafficInterceptor",
    "EmulatorManager",
    "MobileTestConfig",
    "MobileTestResult",
    "SirenMobileController",
    "DANGEROUS_PERMISSIONS",
    "OWASP_MOBILE_TOP10",
    # APK / IPA Static Analyzer
    "AnalysisDepth",
    "ComponentType",
    "ManifestAnalysis",
    "DexAnalysis",
    "CertificateAnalysis",
    "NetworkSecurityAnalysis",
    "NativeLibAnalysis",
    "StorageAnalysis",
    "FullAnalysisResult",
    "BinaryXMLParser",
    "DexStringExtractor",
    "ELFAnalyzer",
    "ManifestAnalyzer",
    "DexDeepAnalyzer",
    "NetworkSecurityConfigAnalyzer",
    "IPAPlistAnalyzer",
    "CertificateAnalyzer",
    "StoragePatternAnalyzer",
    "PlayStorePolicyChecker",
    "SirenAPKAnalyzer",
    # Dynamic Mobile Analysis
    "HookType",
    "MobileExploitResult",
    "HookResult",
    "ContentProviderResult",
    "DeepLinkResult",
    "MemoryScanResult",
    "DynamicTestResult",
    "FridaScriptLibrary",
    "ContentProviderExploiter",
    "DeepLinkFuzzer",
    "BroadcastExploiter",
    "IPCExploitEngine",
    "MemoryScanner",
    "ScreenshotEngine",
    "SirenDynamicAnalyzer",
    # Mobile Payloads
    "MobilePayloadCategory",
    "PayloadSeverity",
    "MobilePayload",
    "PayloadSet",
    "DeepLinkPayloads",
    "ContentProviderPayloads",
    "WebViewPayloads",
    "IntentPayloads",
    "BroadcastPayloads",
    "FridaPayloads",
    "NetworkPayloads",
    "iOSPayloads",
    "ADBPayloads",
    "SirenPayloadGenerator",
    # Attack Graph Engine
    "NodeType",
    "EdgeType",
    "RiskTier",
    "AttackNode",
    "AttackEdge",
    "AttackChain",
    "BlastRadiusResult",
    "LynchpinResult",
    "AttackSurfaceSnapshot",
    "GraphAnalysisResult",
    "AttackGraph",
    "AttackGraphBuilder",
    "SirenAttackGraphAnalyzer",
    # Threat Intelligence Correlation
    "KillChainPhase",
    "ThreatLevel",
    "ComplianceFramework",
    "IndustryVertical",
    "ATTACKMapping",
    "ThreatActorCorrelation",
    "ComplianceViolation",
    "ExploitPrediction",
    "ThreatHuntQuery",
    "ThreatIntelReport",
    "SirenThreatIntel",
    # CORTEX — Cognitive Core
    "BayesianNetwork", "BeliefState", "BayesianNode",
    "EvidenceCollector", "PosteriorCalculator", "HypothesisRanker",
    "SirenBayesianEngine",
    "VulnGenome", "DNAExtractor", "GeneticComparator",
    "LineageTracker", "MutationAnalyzer", "PredictiveGenetics", "SirenVulnDNA",
    "ExploitPrimitive", "PrimitiveMapper", "ChainCandidate",
    "ChainSynthesizer", "ChainScorer", "ChainOptimizer",
    "ChainExecutor", "SirenExploitSynthesis",
    "AttackPersona", "PersonaLibrary", "BehaviorSimulator",
    "PersonaStrategySelector", "SirenAttackPersonaEngine",
    "KnowledgeNode", "KnowledgeEdge", "KnowledgeGraph",
    "GraphQueryEngine", "SirenKnowledgeGraph",
    "EvasionGenerator", "EvasionResult", "FeatureAnalyzer",
    "MLModelProber", "PerturbationEngine", "SirenAdversarialML",
    "ActionLibrary", "AttackPlan", "PlanOptimizer",
    "PlanSearchEngine", "SirenAttackPlanner",
    "DeductiveEngine", "InferenceRule", "ReasoningChain",
    "ReasoningResult", "ReasoningReport",
    "Evidence", "Hypothesis", "SirenCognitiveReasoner",
    # INTELLIGENCE — Defensive & Analytical
    "WAFRuleGenerator", "FirewallRuleGenerator", "IDSSignatureGenerator",
    "SIGMARuleGenerator", "CodePatchGenerator", "ConfigFixGenerator",
    "SirenDefensiveMirror",
    "NarrativeChapter", "AttackTimeline", "NarrativeEngine",
    "AudienceAdapter", "SirenAttackNarrative",
    "DorkEngine", "IdentityResolver", "OSINTGraph", "SirenOSINTCorrelator",
    "FingerprintResult", "SignatureDB", "SirenDeepFingerprint",
    "CVEDatabase", "PredictionReport", "SirenCVEPredictor",
    "PhishingTemplateGen", "PretextBuilder", "VishingScriptGen",
    "SMiShingGen", "DomainLookalikeGen", "SocialEngReport",
    "SirenSocialEngineer",
    "IOCExtractor", "STIXExporter", "YARARuleGenerator",
    "ThreatSIGMARuleGenerator", "PlaybookLibrary", "SirenThreatHunter",
    # META — Self-Evolution
    "PatternLearner", "StrategyOptimizer", "PayloadEvolver",
    "TechniqueRanker", "FalsePositiveLearner", "TargetProfiler",
    "EvolutionDB", "SirenSelfEvolution",
    "SimilarityEngine", "StrategyChain", "StrategyPersistence",
    "StrategyRecommendation", "StrategyRecord", "SirenStrategyDB",
    "BottleneckInfo", "OperationProfile", "OptimizationSuggestion",
    "ThroughputTracker", "Timer", "SirenPerformanceProfiler",
    # ARSENAL — Extended Weapons
    "ProtocolField", "ProtocolSignature", "BinaryFieldExtractor",
    "FuzzingSeedGenerator", "SirenProtocolDissector",
    "SupplyChainFinding", "SupplyChainReport", "ManifestParser",
    "LicenseAuditor", "DependencyGraphBuilder", "SirenSupplyChain",
    "ContainerFinding", "ContainerAuditReport", "DockerfileAnalyzer",
    "KubernetesAnalyzer", "SirenContainerSecurity",
    "GraphQLField", "GraphQLSchema", "IntrospectionQueryBuilder",
    "QueryGenerator", "SirenGraphQLEngine",
    "WSFrame", "WSMessage", "WSReport",
    "WSFuzzGenerator", "SirenWebSocketEngine",
    "CloudCredential", "CloudAsset", "CloudFinding", "CloudPrivEscPath",
    "MetadataExploiter", "S3BucketScanner", "AWSExploiter",
    "GCPExploiter", "AzureExploiter", "CloudPrivEscChain",
    "IAMAnalyzer", "CloudCredentialHarvester", "SirenCloudAttacker",
    "IoTFinding", "IoTDevice", "IoTReport", "DefaultCredDB",
    "IoTFingerprinter", "MQTTExploiter", "CoAPExploiter",
    "UPnPScanner", "ModbusExploiter", "BACnetScanner",
    "AMQPAnalyzer", "SirenIoTEngine",
    "DASTFinding", "DASTReport", "CrawlerEngine",
    "ParameterFuzzer", "AuthenticatedScanner", "SirenDASTEngine",
    "SASTFinding", "SASTReport", "SourceDetector", "TaintFlow",
    "SASTScanConfig", "SirenSASTEngine",
    "ADFinding", "ADReport", "LDAPEnumerator",
    "BloodHoundAnalyzer", "DomainInfo", "SirenADAttacker",
    "FirmwareFinding", "FirmwareReport", "FirmwareMetadata",
    "EntropyAnalyzer", "BinaryDelta", "SirenFirmwareAnalyzer",
    "LLMFinding", "LLMSecurityReport", "PromptInjector",
    "JailbreakEngine", "SystemPromptExtractor",
    "DataExfiltrator", "SirenLLMAttacker",
    "NetworkFinding", "NetworkReport", "NetworkMapper",
    "ServiceExploiter", "ProtocolAttacker",
    "CredentialHarvester", "TunnelManager",
    "SirenNetworkExploiter",
    # EVASION — Bypass & Obfuscation
    "WAFProfile", "WAFFingerprinter", "PayloadTransformer",
    "PayloadMutator", "EncodingChainer", "BypassTechnique",
    "BypassResult", "WAFBypassReport", "SirenWAFBypass",
    "PacketFragmenter", "TimingEvader", "ProtocolAbuser",
    "TrafficMixer", "SessionSplitter",
    "IDSFinding", "IDSEvasionReport",
    "SirenIDSEvasion",
    "JSObfuscator", "SQLObfuscator", "CMDObfuscator",
    "HTMLObfuscator", "ShellObfuscator", "PowerShellObfuscator",
    "ObfuscationResult", "ObfuscationReport",
    "SirenPayloadObfuscator",
    # AUTOMATION — Campaigns & Monitoring
    "Campaign", "CampaignTask", "CampaignPhase",
    "CampaignTemplates", "CampaignPersistence", "SirenCampaignManager",
    "MonitorTarget", "Alert", "ContentDiffer",
    "AlertSeverity", "SirenContinuousMonitor",
    "CorrelatedFinding", "CorrelationRule", "CrossScanPattern",
    "DeduplicationEngine", "SirenResultCorrelator",
    # OUTPUT — Compliance, Risk & Remediation
    "ComplianceStandard", "ComplianceControl", "ComplianceGap",
    "ComplianceReport", "SirenComplianceMapper",
    "BusinessContext", "RiskFactor", "RiskScore",
    "RiskMatrix", "SirenRiskScorer",
    "RemediationStep", "RemediationPlan", "FixTemplate",
    "PriorityQueue", "SirenRemediationGenerator",
    # API Security Engine
    "APISeverity", "APIVulnCategory", "ScopeLevel",
    "APIEndpoint", "DataExposureFinding", "APISecurityFinding", "APIAuditResult",
    "APISecurityHTTP", "BrokenAccessControlScanner", "DataExposureScanner",
    "JWTSecurityScanner", "RateLimitScanner", "UserEnumerationScanner",
    "ChannelBypassScanner", "AuthGateBypassScanner", "HeaderPermutationFuzzer",
    "SirenAPISecurityEngine",
    # Cloud & JWT Advanced Scanner
    "CloudFunctionScanner", "JWTAdvancedScanner",
    "CORSAdvancedScanner", "JSONInteropScanner",
    # Pentest Engine
    "PentestPhase", "OWASPTop10", "OWASPAPITop10",
    "PentestAttackVector", "PentestSeverity",
    "PentestFinding", "PentestConfig", "PentestResult",
    "MassAssignmentScanner", "RaceConditionScanner",
    "BusinessLogicScanner", "ComplianceChecker",
    "SirenPentestEngine",
    # Pentest ↔ API Security Integration
    "AgentResult", "PentestAPISecurityAgent",
]
